name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install Shuttle
      run: cargo install cargo-shuttle
    - name: Stop last deployment
      run: shuttle deployment stop 
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
    - name: Deploy
      run: shuttle deploy --id proj_01JKYX5DMN5VDJEEKY123M6VVB
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
