name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install Shuttle
      run: curl -sSfL https://www.shuttle.dev/install | bash
    - name: Stop last deployment
      run: shuttle deployment stop 
    - name: Deploy
      run: shuttle deploy
